name: Build OpenShockClock

on:
  push:
    tags:
      - "v*" # Triggers on any tag starting with 'v'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: OpenShockClock.exe
            asset_name: OpenShockClock-Windows.zip
          - os: ubuntu-latest
            output_name: OpenShockClock
            asset_name: OpenShockClock-Linux.zip
          - os: macos-latest
            output_name: OpenShockClock
            asset_name: OpenShockClock-MacOS.zip

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create spec file on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          echo # -*- mode: python ; coding: utf-8 -*- > openshockclock.spec
          echo. >> openshockclock.spec
          echo block_cipher = None >> openshockclock.spec
          echo. >> openshockclock.spec
          echo added_files = [ >> openshockclock.spec
          echo     ('singleuser/static', 'static'), >> openshockclock.spec
          echo     ('singleuser/templates', 'templates'), >> openshockclock.spec
          echo ] >> openshockclock.spec
          echo. >> openshockclock.spec
          echo a = Analysis( >> openshockclock.spec
          echo     ['singleuser/app.py'], >> openshockclock.spec
          echo     pathex=[], >> openshockclock.spec
          echo     binaries=[], >> openshockclock.spec
          echo     datas=added_files, >> openshockclock.spec
          echo     hiddenimports=['webview', 'PIL', 'flask', 'configparser', 'requests'], >> openshockclock.spec
          echo     hookspath=[], >> openshockclock.spec
          echo     hooksconfig={}, >> openshockclock.spec
          echo     runtime_hooks=[], >> openshockclock.spec
          echo     excludes=['kivy'], >> openshockclock.spec
          echo     win_no_prefer_redirects=False, >> openshockclock.spec
          echo     win_private_assemblies=False, >> openshockclock.spec
          echo     cipher=block_cipher, >> openshockclock.spec
          echo     noarchive=False, >> openshockclock.spec
          echo ) >> openshockclock.spec
          echo. >> openshockclock.spec
          echo pyz = PYZ( >> openshockclock.spec
          echo     a.pure, >> openshockclock.spec
          echo     a.zipped_data, >> openshockclock.spec
          echo     cipher=block_cipher >> openshockclock.spec
          echo ) >> openshockclock.spec
          echo. >> openshockclock.spec
          echo exe = EXE( >> openshockclock.spec
          echo     pyz, >> openshockclock.spec
          echo     a.scripts, >> openshockclock.spec
          echo     a.binaries, >> openshockclock.spec
          echo     a.zipfiles, >> openshockclock.spec
          echo     a.datas, >> openshockclock.spec
          echo     [], >> openshockclock.spec
          echo     name='OpenShockClock', >> openshockclock.spec
          echo     debug=False, >> openshockclock.spec
          echo     bootloader_ignore_signals=False, >> openshockclock.spec
          echo     strip=False, >> openshockclock.spec
          echo     upx=True, >> openshockclock.spec
          echo     upx_exclude=[], >> openshockclock.spec
          echo     runtime_tmpdir=None, >> openshockclock.spec
          echo     console=True, >> openshockclock.spec
          echo     disable_windowed_traceback=False, >> openshockclock.spec
          echo     target_arch=None, >> openshockclock.spec
          echo     codesign_identity=None, >> openshockclock.spec
          echo     entitlements_file=None, >> openshockclock.spec
          echo     icon='singleuser/static/favicon.ico' >> openshockclock.spec
          echo ) >> openshockclock.spec

      - name: Create spec file on Unix
        if: matrix.os != 'windows-latest'
        run: |
          cat > openshockclock.spec << 'EOF'
          # -*- mode: python ; coding: utf-8 -*-

          block_cipher = None

          added_files = [
              ('singleuser/static', 'static'),
              ('singleuser/templates', 'templates'),
          ]

          a = Analysis(
              ['singleuser/app.py'],
              pathex=[],
              binaries=[],
              datas=added_files,
              hiddenimports=[
                  'webview',
                  'PIL',
                  'flask',
                  'configparser',
                  'requests'
              ],
              hookspath=[],
              hooksconfig={},
              runtime_hooks=[],
              excludes=['kivy'],
              win_no_prefer_redirects=False,
              win_private_assemblies=False,
              cipher=block_cipher,
              noarchive=False,
          )

          pyz = PYZ(
              a.pure,
              a.zipped_data,
              cipher=block_cipher
          )

          exe = EXE(
              pyz,
              a.scripts,
              a.binaries,
              a.zipfiles,
              a.datas,
              [],
              name='OpenShockClock',
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=True,
              upx_exclude=[],
              runtime_tmpdir=None,
              console=True,
              disable_windowed_traceback=False,
              target_arch=None,
              codesign_identity=None,
              entitlements_file=None,
              icon='singleuser/static/favicon.ico'
          )
          EOF

      - name: Build with PyInstaller
        run: pyinstaller openshockclock.spec

      - name: Create ZIP archive
        run: |
          cd dist
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a ../${{ matrix.asset_name }} OpenShockClock.exe
          else
            zip -r ../${{ matrix.asset_name }} OpenShockClock
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: ${{ matrix.asset_name }}

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            *-build/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
